// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

int main(int argc, char *argv[]){
	
	int currentSum = 0;
	int fib1 = 0;
	int fib2 = 1;
	int nextFib = fib1 + fib2;
	
//	printf("%d\n", fib1);
//	printf("%d\n", fib2);
	
	while (nextFib <= 4000000){
		
		if (nextFib % 2 == 0){
			currentSum += nextFib;
		}
		
		//printf("%d\n", nextFib);
		
		fib1 = fib2;
		fib2 = nextFib;
		nextFib = fib1 + fib2;
	}
	
	printf("Sum of even fibonacci terms, not exceeding 4,000,000: %d", currentSum);
			
	return 0;
}
